### ISSUE TITLE
Downloading Citadel ... after Update

### ISSUE THREAD

**Issue by CoReYeDe** [runcitadel/compose-nonfree#7]
![image](https://user-images.githubusercontent.com/22613068/139239658-732e75b5-587c-4611-9937-7060e28ecb9e.png)

After updating to 0.4.10 i get this screen (still since 4 hours)
Switch from umbrel to citadel was running smoothly and also 2 updates from citadel.

Any Ideas to troubleshoot?

**Comment by CoReYeDe** [comment]
![image](https://user-images.githubusercontent.com/22613068/139240212-e8da4b6e-62f9-467b-98fe-186bc647d7ca.png)

**Comment by AaronDewes** [comment]
I'm sorry for the delayed response, are you still experiencing this?

If yes, try a manual update via SSH

`~/umbrel/scripts/update/update --repo runcitadel/compose-nonfree#main`

**Comment by CoReYeDe** [comment]
Thanks. I have reflashed the sd-card without wiping the ssd and then it work again..
dont know what happen but until now it work..
